default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root

development:
  <<: *default
  database: classpro_demo_development
  host: localhost
  password: classpro2930

production:
  <<: *default
  database: classpro_demo_production
  host: localhost
  password: classpro@2930